# Análise comparativa de modelos

## Visão geral do notebook

### 1. Obtenção de dados

#### 1.1. Configuração do Ambiente: Importação das Bibliotecas Necessárias para Análise e Modelagem

In [5]:
# Importação de bibliotecas

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
import seaborn as sns

from IPython.display import display, Markdown

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import ShuffleSplit, GridSearchCV, KFold, cross_validate
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#### 1.2. Carregamento dos Dados e Inspeção Inicial

In [12]:
# Exibição da descrição do conjunto de dados
display(Markdown(
    "O conjunto de dados, proveniente da plataforma Kaggle, contém informações sobre os padrões de sono de indivíduos, identificados por um 'ID do Sujeito' único. Inclui dados sobre idade, gênero, horário de dormir e acordar, duração do sono, eficiência do sono, porcentagens de sono REM, profundo e leve, número de despertares, consumo de cafeína e álcool antes de dormir, status de fumante e frequência de exercícios.\n\n"
    "A variável dependente é a **Sleep eficciency**. As variáveis preditoras que podem influenciar a eficiência do sono são **ID**, **age**, **gender**, **Bedtime**, **Wakeup time**, **Sleep duration**, **REM sleep percentage**, **Deep sleep percentage**, **Light sleep percentage**, **Awakenings**, **Caffeine consumption**, **Alcohol consumption**, **Smoking status**, **Exercise frequency**."
))

# Carregamento dos dados do arquivo CSV
df = pd.read_csv("../data/raw/sleep_efficiency.csv")
display(df.head())

O conjunto de dados, proveniente da plataforma Kaggle, contém informações sobre os padrões de sono de indivíduos, identificados por um 'ID do Sujeito' único. Inclui dados sobre idade, gênero, horário de dormir e acordar, duração do sono, eficiência do sono, porcentagens de sono REM, profundo e leve, número de despertares, consumo de cafeína e álcool antes de dormir, status de fumante e frequência de exercícios.

A variável dependente é a **Sleep eficciency**. As variáveis preditoras que podem influenciar a eficiência do sono são **ID**, **age**, **gender**, **Bedtime**, **Wakeup time**, **Sleep duration**, **REM sleep percentage**, **Deep sleep percentage**, **Light sleep percentage**, **Awakenings**, **Caffeine consumption**, **Alcohol consumption**, **Smoking status**, **Exercise frequency**.

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

#### 1.3. Dicionário de dados

In [14]:
# Carregamento do dicionário de dados

df_dict = pd.read_csv("../data/external/dictionary.csv")
display(df_dict)

display(Markdown(
    "---\n"
    "* O conjunto de dados inclui 15 variáveis, sendo 9 quatitativas discretas, 4 quantitativas contínuas, de 2 qualitativas nominais"
    "\n\n"
))

,variavel,descrição,tipo,subtipo
0,ID,Identificador único do indivíduo,qualitativa,nominal
1,Age,Idade do indivíduo em anos.,quantitativa,discreta
2,Gender,Gênero do indivíduo.,qualitativa,nominal
3,Bedtime,Hora em que o indivíduo foi para a cama. Forma...,qualitativa,nominal
4,Wakeup time,Hora em que o indivíduo acordou. Formato de da...,qualitativa,nominal
5,Sleep duration,Duração total do sono do indivíduo em horas,quantitativa,contínua
6,Sleep efficiency,Eficiência do sono do indivíduo,quantitativa,contínua
7,REM sleep percentage,Percentual de sono REM (Rapid Eye Movement) do...,quantitativa,discreta
8,Deep sleep percentage,Percentual de sono profundo do indivíduo em re...,quantitativa,discreta
9,Light sleep percentage,Percentual de sono leve do indivíduo em relaçã...,quantitativa,discreta
10,Awakenings,Número de vezes que o indivíduo despertou dura...,quantitativa,discreta
11,Caffeine consumption,Quantidade de cafeína consumida pelo indivíduo...,quantitativa,contínua
12,Alcohol consumption,Quantidade de álcool consumida pelo indivíduo ...,quantitativa,contínua
13,Smoking status,Status de fumante do indivíduo. Possíveis valo...,qualitativa,nominal
14,Exercise frequency,Frequência com que o indivíduo pratica exercíc...,quantitativa,discreta

---
* O conjunto de dados inclui 15 variáveis, sendo 9 quatitativas discretas, 4 quantitativas contínuas, de 2 qualitativas nominais

#### 1.4. Informações gerais do DataFrame

#### 1.5. Estatística descritiva do conjunto de dados

### 2. Preparação de dados

#### 2.1. Preparação das Variáveis para Análise

#### 2.2. Verificação de Dados Faltantes

#### 2.2.1. Tratamento de dados faltantes

#### 2.3. Identificação e Visualização de Outliers usando o Método do IQR

#### 2.3.1 Tratamento de dados com outliers

#### 2.4. Codificação de variáveis

#### 2.5. Normalização dos Dados

### 3. Seleção de modelos