In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/KesavaS2/Kesava_Menezes/master/data/raw/sleep_efficiency.csv")
df.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [4]:
df.to_csv("../data/raw/sleep_efficiency.csv",index=False)

In [5]:
dicionario = pd.DataFrame ([
{
"variavel": "ID",
"descrição": " Identificador único do indivíduo",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Age",
"descrição": " Idade do indivíduo em anos.",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Gender",
"descrição": " Gênero do indivíduo.",
"tipo": "qualitativa",
"subtipo": "nominal"
},{
"variavel": "Bedtime",
"descrição": "Hora em que o indivíduo foi para a cama. Formato de data e hora: YYYY-MM-DD HH:MM",
"tipo": "quantitativa",
"subtipo": "contínua"
},{
"variavel": "Wakeup time",
"descrição": "Hora em que o indivíduo acordou. Formato de data e hora: YYYY-MM-DD HH:MM",
"tipo": "quantitativa",
"subtipo": "contínua"
},{
"variavel": "Sleep duration",
"descrição": "Duração total do sono do indivíduo em horas",
"tipo": "quantitativa",
"subtipo": "contínua"
},{
"variavel": "Sleep efficiency",
"descrição": "Eficiência do sono do indivíduo",
"tipo": "quantitativa",
"subtipo": "contínua"
},{
"variavel": "REM sleep percentage",
"descrição": "Percentual de sono REM (Rapid Eye Movement) do indivíduo em relação ao tempo total de sono",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Deep sleep percentage",
"descrição": "Percentual de sono profundo do indivíduo em relação ao tempo total de sono",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Light sleep percentage",
"descrição": "Percentual de sono leve do indivíduo em relação ao tempo total de sono.",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Awakenings",
"descrição": "Número de vezes que o indivíduo despertou durante o período de sono",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Caffeine consumption",
"descrição": "Quantidade de cafeína consumida pelo indivíduo em miligramas (mg) durante o dia",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Alcohol consumption",
"descrição": "Quantidade de álcool consumida pelo indivíduo em gramas (g) durante o dia",
"tipo": "quantitativa",
"subtipo": "discreta"
},{
"variavel": "Smoking status",
"descrição": "Status de fumante do indivíduo. Possíveis valores incluem Yes (Sim) e No (Não)",
"tipo": "qualitativa",
"subtipo": "nominal"
},{
"variavel": "Exercise frequency",
"descrição": "Frequência com que o indivíduo pratica exercícios físicos durante a semana",
"tipo": "quantitativa",
"subtipo": "discreta"
}
])

In [6]:
dicionario.to_csv("../data/external/dictionary.csv",index=False)

In [7]:
dicionario

,variavel,descrição,tipo,subtipo
0,ID,Identificador único do indivíduo,quantitativa,discreta
1,Age,Idade do indivíduo em anos.,quantitativa,discreta
2,Gender,Gênero do indivíduo.,qualitativa,nominal
3,Bedtime,Hora em que o indivíduo foi para a cama. Forma...,quantitativa,contínua
4,Wakeup time,Hora em que o indivíduo acordou. Formato de da...,quantitativa,contínua
5,Sleep duration,Duração total do sono do indivíduo em horas,quantitativa,contínua
6,Sleep efficiency,Eficiência do sono do indivíduo,quantitativa,contínua
7,REM sleep percentage,Percentual de sono REM (Rapid Eye Movement) do...,quantitativa,discreta
8,Deep sleep percentage,Percentual de sono profundo do indivíduo em re...,quantitativa,discreta
9,Light sleep percentage,Percentual de sono leve do indivíduo em relaçã...,quantitativa,discreta
10,Awakenings,Número de vezes que o indivíduo despertou dura...,quantitativa,discreta
11,Caffeine consumption,Quantidade de cafeína consumida pelo indivíduo...,quantitativa,discreta
12,Alcohol consumption,Quantidade de álcool consumida pelo indivíduo ...,quantitativa,discreta
13,Smoking status,Status de fumante do indivíduo. Possíveis valo...,qualitativa,nominal
14,Exercise frequency,Frequência com que o indivíduo pratica exercíc...,quantitativa,discreta